import { WidgetConfig } from '../types';

export function generatePowerShellScript(config: WidgetConfig): string {
  const {
    school,
    ddays,
    timetable,
    theme,
    opacity,
    alwaysOnTop,
    snapMargin,
    mealSwitchTime,
    showAllergies,
  } = config;

  const [switchH, switchM] = mealSwitchTime.split(':').map(Number);
  const switchHour = isNaN(switchH) ? 13 : switchH;
  const switchMinute = isNaN(switchM) ? 30 : switchM;

  // JSON serialized data
  const timetableJson = JSON.stringify(timetable).replace(/'/g, "''");
  const ddaysJson = JSON.stringify(ddays).replace(/'/g, "''");

  // Determine colors based on theme
  let bgGradient1 = '#F01A1F2C';
  let bgGradient2 = '#F011151E';
  let cardBg = '#22FFFFFF';
  let cardBorder = '#33FFFFFF';
  let textPrimary = '#FFFFFF';
  let textSecondary = '#94A3B8';
  let accentColor = '#3B82F6';
  let badgeBg = '#1E293B';

  if (theme === 'light-acrylic') {
    bgGradient1 = '#F4FFFFFF';
    bgGradient2 = '#E8F1F5F9';
    cardBg = '#88FFFFFF';
    cardBorder = '#D0E2E8F0';
    textPrimary = '#0F172A';
    textSecondary = '#64748B';
    accentColor = '#2563EB';
    badgeBg = '#F1F5F9';
  } else if (theme === 'emerald-glass') {
    bgGradient1 = '#F006201B';
    bgGradient2 = '#F0021310';
    cardBg = '#1810B981';
    cardBorder = '#3034D399';
    textPrimary = '#F0FDF4';
    textSecondary = '#86EFAC';
    accentColor = '#10B981';
    badgeBg = '#064E3B';
  } else if (theme === 'indigo-glass') {
    bgGradient1 = '#F01E1B4B';
    bgGradient2 = '#F0111030';
    cardBg = '#206366F1';
    cardBorder = '#40818CF8';
    textPrimary = '#EEF2FF';
    textSecondary = '#A5B4FC';
    accentColor = '#6366F1';
    badgeBg = '#312E81';
  }

  // Build script using string array join to prevent template literal backtick collisions
  const lines: string[] = [
    '<#',
    '================================================================================',
    '  [NEWSchoolWidget - 학교 생활 윈도우 위젯]',
    '  - 환경: Windows 10 / 11 PowerShell + WPF Native GUI',
    '  - 주요 기능:',
    '    1) 테두리 없는 깔끔한 모던 반투명 아크릴 위젯',
    '    2) 마우스 드래그 이동 & 손 떼면 모니터 우측 상단 자동 스냅 (멀티 모니터 완벽 지원)',
    '    3) 실시간 날짜, 시계 및 시험/방학 D-Day 카운터',
    '    4) 요일별 교사/학생 시간표',
    '    5) 나이스(NEIS) 오픈 API 실시간 급식 (13:30 기준 오늘/내일 급식 자동 전환)',
    '    6) 할 일(TO-DO) 리스트 (추가/완료/삭제, 파일 자동 저장, 동적 높이 조절)',
    '================================================================================',
    '#>',
    '',
    '# 0. STA 모드 및 ExecutionPolicy 자동 보장 자가 재실행 (우클릭 직접 실행 시 필수)',
    'if ($PSCommandPath -and ([System.Threading.Thread]::CurrentThread.GetApartmentState() -ne [System.Threading.ApartmentState]::STA)) {',
    '    Start-Process powershell.exe -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Sta -WindowStyle Hidden -File `"$PSCommandPath`""',
    '    Exit',
    '}',
    '',
    'try {',
    '    # 1. 필수 .NET 어셈블리 로드',
    '    Add-Type -AssemblyName PresentationFramework',
    '    Add-Type -AssemblyName PresentationCore',
    '    Add-Type -AssemblyName WindowsBase',
    '    Add-Type -AssemblyName System.Windows.Forms',
    '    Add-Type -AssemblyName System.Drawing',
    '    Add-Type -AssemblyName System.Xml',
    '',
    '    # 2. 전역 설정 데이터',
    `    $Global:OfficeCode    = "${school.officeCode}"`,
    `    $Global:SchoolCode    = "${school.schoolCode}"`,
    `    $Global:SchoolName    = "${school.schoolName}"`,
    `    $Global:SnapMargin    = ${snapMargin}`,
    `    $Global:SwitchHour    = ${switchHour}`,
    `    $Global:SwitchMinute  = ${switchMinute}`,
    `    $Global:ShowAllergies = $${showAllergies ? 'True' : 'False'}`,
    '',
    '    # 할 일 파일 경로 (내 문서\\NEWSchoolWidget\\todos.json)',
    '    $Global:TodoDir  = [System.IO.Path]::Combine($env:USERPROFILE, "Documents", "NEWSchoolWidget")',
    '    $Global:TodoFile = [System.IO.Path]::Combine($Global:TodoDir, "todos.json")',
    '    if (!(Test-Path $Global:TodoDir)) { New-Item -ItemType Directory -Path $Global:TodoDir -Force | Out-Null }',
    '',
    `    $Global:TimetableJson = '${timetableJson}'`,
    '    $Global:TimetableData = $Global:TimetableJson | ConvertFrom-Json',
    '',
    `    $Global:DDaysJson = '${ddaysJson}'`,
    '    $Global:DDaysData = $Global:DDaysJson | ConvertFrom-Json',
    '',
    '    # 3. WPF XAML 정의 (테두리 없는 창, 반투명 효과, 자동 높이)',
    '    $xamlString = @"',
    '<Window',
    '    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
    '    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"',
    '    Title="NEWSchoolWidget - 학교 생활 위젯"',
    '    WindowStyle="None"',
    '    AllowsTransparency="True"',
    '    Background="Transparent"',
    `    Topmost="${alwaysOnTop ? 'True' : 'False'}"`,
    '    ShowInTaskbar="True"',
    '    SizeToContent="Height"',
    '    Width="340"',
    '    UseLayoutRounding="True"',
    '    SnapsToDevicePixels="True">',
    '',
    `    <Border Margin="10" CornerRadius="18" BorderThickness="1" BorderBrush="${cardBorder}" Opacity="${opacity}">`,
    '        <Border.Background>',
    '            <LinearGradientBrush StartPoint="0,0" EndPoint="1,1">',
    `                <GradientStop Color="${bgGradient1}" Offset="0.0"/>`,
    `                <GradientStop Color="${bgGradient2}" Offset="1.0"/>`,
    '            </LinearGradientBrush>',
    '        </Border.Background>',
    '        <Border.Effect>',
    '            <DropShadowEffect BlurRadius="18" ShadowDepth="4" Direction="270" Color="#000000" Opacity="0.45"/>',
    '        </Border.Effect>',
    '',
    '        <Grid Margin="16">',
    '            <Grid.RowDefinitions>',
    '                <RowDefinition Height="Auto"/>',
    '                <RowDefinition Height="Auto"/>',
    '                <RowDefinition Height="Auto"/>',
    '                <RowDefinition Height="Auto"/>',
    '                <RowDefinition Height="Auto"/>',
    '                <RowDefinition Height="Auto"/>',
    '                <RowDefinition Height="Auto"/>',
    '            </Grid.RowDefinitions>',
    '',
    '            <!-- Row 0: Header (학교명, 날짜, 시계, 닫기 버튼) -->',
    '            <Grid Grid.Row="0" Margin="0,0,0,10">',
    '                <Grid.ColumnDefinitions>',
    '                    <ColumnDefinition Width="*"/>',
    '                    <ColumnDefinition Width="Auto"/>',
    '                </Grid.ColumnDefinitions>',
    '                <StackPanel Grid.Column="0">',
    `                    <TextBlock x:Name="TxtSchoolName" Text="${school.schoolName}" FontSize="12" FontWeight="SemiBold" Foreground="${accentColor}"/>`,
    `                    <TextBlock x:Name="TxtCurrentDate" Text="날짜 로딩 중..." FontSize="15" FontWeight="Bold" Foreground="${textPrimary}" Margin="0,2,0,0"/>`,
    `                    <TextBlock x:Name="TxtCurrentTime" Text="00:00:00" FontSize="11" Foreground="${textSecondary}"/>`,
    '                </StackPanel>',
    '                <StackPanel Grid.Column="1" Orientation="Horizontal" VerticalAlignment="Top">',
    `                    <Button x:Name="BtnRefresh" Content="새로고침" Height="22" Padding="6,0" Margin="0,0,4,0" Background="#33000000" Foreground="${textSecondary}" BorderBrush="${cardBorder}" BorderThickness="1" Cursor="Hand" FontSize="10" ToolTip="새로고침"/>`,
    `                    <Button x:Name="BtnClose" Content="✕" Width="22" Height="22" Background="#33000000" Foreground="${textSecondary}" BorderBrush="${cardBorder}" BorderThickness="1" Cursor="Hand" FontSize="11" ToolTip="위젯 닫기"/>`,
    '                </StackPanel>',
    '            </Grid>',
    '',
    '            <!-- Row 1: D-Day Badges -->',
    '            <WrapPanel x:Name="PnlDDays" Grid.Row="1" Margin="0,0,0,10" />',
    '',
    '            <!-- Row 2: Divider -->',
    `            <Rectangle Grid.Row="2" Height="1" Fill="${cardBorder}" Margin="0,0,0,10"/>`,
    '',
    '            <!-- Row 3: Timetable Section -->',
    `            <Border Grid.Row="3" Background="${cardBg}" BorderBrush="${cardBorder}" BorderThickness="1" CornerRadius="12" Padding="10" Margin="0,0,0,10">`,
    '                <StackPanel>',
    '                    <Grid Margin="0,0,0,6">',
    `                        <TextBlock Text="📅 오늘의 시간표" FontSize="12" FontWeight="Bold" Foreground="${textPrimary}"/>`,
    `                        <TextBlock x:Name="TxtDayOfWeek" Text="(월요일)" HorizontalAlignment="Right" FontSize="11" Foreground="${textSecondary}"/>`,
    '                    </Grid>',
    '                    <StackPanel x:Name="PnlTimetable" Margin="0,2,0,0"/>',
    '                </StackPanel>',
    '            </Border>',
    '',
    '            <!-- Row 4: NEIS Meal Section -->',
    `            <Border Grid.Row="4" Background="${cardBg}" BorderBrush="${cardBorder}" BorderThickness="1" CornerRadius="12" Padding="10" Margin="0,0,0,10">`,
    '                <StackPanel>',
    '                    <Grid Margin="0,0,0,6">',
    '                        <StackPanel Orientation="Horizontal">',
    '                            <TextBlock Text="🍱 " FontSize="12"/>',
    `                            <TextBlock x:Name="TxtMealTitle" Text="오늘의 급식" FontSize="12" FontWeight="Bold" Foreground="${textPrimary}"/>`,
    '                        </StackPanel>',
    `                        <TextBlock x:Name="TxtMealTimeBadge" Text="13:30 기준" HorizontalAlignment="Right" FontSize="10" Foreground="${accentColor}"/>`,
    '                    </Grid>',
    `                    <TextBlock x:Name="TxtMealMenu" Text="급식 정보를 불러오는 중입니다..." TextWrapping="Wrap" LineHeight="18" FontSize="12" Foreground="${textPrimary}"/>`,
    `                    <TextBlock x:Name="TxtMealCalories" Text="" FontSize="10" Foreground="${textSecondary}" Margin="0,4,0,0"/>`,
    '                </StackPanel>',
    '            </Border>',
    '',
    '            <!-- Row 5: To-Do Section (동적 크기 조절) -->',
    `            <Border Grid.Row="5" Background="${cardBg}" BorderBrush="${cardBorder}" BorderThickness="1" CornerRadius="12" Padding="10" Margin="0,0,0,10">`,
    '                <StackPanel>',
    '                    <Grid Margin="0,0,0,6">',
    `                        <TextBlock Text="✅ 오늘 할 일 (TO-DO)" FontSize="12" FontWeight="Bold" Foreground="${textPrimary}"/>`,
    `                        <TextBlock x:Name="TxtTodoCount" Text="0개 남음" HorizontalAlignment="Right" FontSize="11" Foreground="${textSecondary}"/>`,
    '                    </Grid>',
    '                    ',
    '                    <!-- Todo Input Box -->',
    '                    <Grid Margin="0,0,0,8">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="Auto"/>',
    '                        </Grid.ColumnDefinitions>',
    `                        <TextBox x:Name="TxtNewTodo" Grid.Column="0" Height="26" Background="#22000000" Foreground="${textPrimary}" BorderBrush="${cardBorder}" BorderThickness="1" Padding="6,3" VerticalContentAlignment="Center" FontSize="11"/>`,
    `                        <Button x:Name="BtnAddTodo" Grid.Column="1" Content="추가" Width="44" Height="26" Margin="4,0,0,0" Background="${accentColor}" Foreground="#FFFFFF" FontWeight="Bold" BorderThickness="0" Cursor="Hand" FontSize="11"/>`,
    '                    </Grid>',
    '',
    '                    <!-- Dynamic Items List -->',
    '                    <StackPanel x:Name="PnlTodoList" />',
    '                </StackPanel>',
    '            </Border>',
    '',
    '            <!-- Row 6: Footer Hint -->',
    `            <TextBlock Grid.Row="6" Text="💡 드래그하여 이동 • 손을 떼면 우측 상단 자동 고정" HorizontalAlignment="Center" FontSize="10" Foreground="${textSecondary}"/>`,
    '        </Grid>',
    '    </Border>',
    '</Window>',
    '"@',
    '',
    '    # 4. XML XAML 로더',
    '    $stringReader = New-Object System.IO.StringReader($xamlString)',
    '    $xmlReader = [System.Xml.XmlReader]::Create($stringReader)',
    '    $Global:Window = [System.Windows.Markup.XamlReader]::Load($xmlReader)',
    '',
    '    # 5. UI 컨트롤 바인딩',
    '    $Global:TxtSchoolName    = $Global:Window.FindName("TxtSchoolName")',
    '    $Global:TxtCurrentDate   = $Global:Window.FindName("TxtCurrentDate")',
    '    $Global:TxtCurrentTime   = $Global:Window.FindName("TxtCurrentTime")',
    '    $Global:PnlDDays         = $Global:Window.FindName("PnlDDays")',
    '    $Global:TxtDayOfWeek     = $Global:Window.FindName("TxtDayOfWeek")',
    '    $Global:PnlTimetable     = $Global:Window.FindName("PnlTimetable")',
    '    $Global:TxtMealTitle     = $Global:Window.FindName("TxtMealTitle")',
    '    $Global:TxtMealTimeBadge = $Global:Window.FindName("TxtMealTimeBadge")',
    '    $Global:TxtMealMenu      = $Global:Window.FindName("TxtMealMenu")',
    '    $Global:TxtMealCalories  = $Global:Window.FindName("TxtMealCalories")',
    '    $Global:TxtTodoCount     = $Global:Window.FindName("TxtTodoCount")',
    '    $Global:TxtNewTodo       = $Global:Window.FindName("TxtNewTodo")',
    '    $Global:BtnAddTodo       = $Global:Window.FindName("BtnAddTodo")',
    '    $Global:PnlTodoList      = $Global:Window.FindName("PnlTodoList")',
    '    $Global:BtnClose         = $Global:Window.FindName("BtnClose")',
    '    $Global:BtnRefresh       = $Global:Window.FindName("BtnRefresh")',
    '',
    '    # 6. 마우스 드래그 & 모니터 우측 상단 자동 스냅 (멀티 모니터 완벽 지원)',
    '    $Global:IsDragging = $false',
    '',
    '    $Global:Window.Add_MouseLeftButtonDown({',
    '        param($sender, $e)',
    '        if ($e.OriginalSource -isnot [System.Windows.Controls.TextBox] -and $e.OriginalSource -isnot [System.Windows.Controls.Button] -and $e.OriginalSource -isnot [System.Windows.Controls.CheckBox]) {',
    '            $Global:IsDragging = $true',
    '            $Global:Window.DragMove()',
    '        }',
    '    })',
    '',
    '    $Global:Window.Add_PreviewMouseLeftButtonUp({',
    '        param($sender, $e)',
    '        if ($Global:IsDragging) {',
    '            $Global:IsDragging = $false',
    '            Snap-ToRightTop',
    '        }',
    '    })',
    '',
    '    function Snap-ToRightTop {',
    '        try {',
    '            $cursorPos = [System.Windows.Forms.Cursor]::Position',
    '            $screen = [System.Windows.Forms.Screen]::FromPoint($cursorPos)',
    '            $workArea = $screen.WorkingArea',
    '',
    '            $source = [System.Windows.PresentationSource]::FromVisual($Global:Window)',
    '            $dpiX = 1.0',
    '            $dpiY = 1.0',
    '            if ($source -and $source.CompositionTarget) {',
    '                $dpiX = $source.CompositionTarget.TransformToDevice.M11',
    '                $dpiY = $source.CompositionTarget.TransformToDevice.M22',
    '            }',
    '            if ($dpiX -le 0) { $dpiX = 1.0 }',
    '            if ($dpiY -le 0) { $dpiY = 1.0 }',
    '',
    '            $winWidth = 340',
    '            if ($Global:Window.ActualWidth -gt 50) { $winWidth = $Global:Window.ActualWidth }',
    '            $targetLeft = ($workArea.Right / $dpiX) - $winWidth - $Global:SnapMargin',
    '            $targetTop  = ($workArea.Top / $dpiY) + $Global:SnapMargin',
    '',
    '            $Global:Window.Left = $targetLeft',
    '            $Global:Window.Top  = $targetTop',
    '        } catch {',
    '            $winWidth = 340',
    '            if ($Global:Window.ActualWidth -gt 50) { $winWidth = $Global:Window.ActualWidth }',
    '            $Global:Window.Left = [System.Windows.SystemParameters]::WorkArea.Right - $winWidth - $Global:SnapMargin',
    '            $Global:Window.Top  = [System.Windows.SystemParameters]::WorkArea.Top + $Global:SnapMargin',
    '        }',
    '    }',
    '',
    '    # 7. D-Day 렌더링 함수',
    '    function Update-DDays {',
    '        $Global:PnlDDays.Children.Clear()',
    '        $today = [DateTime]::Today',
    '',
    '        foreach ($item in $Global:DDaysData) {',
    '            try {',
    '                $target = [DateTime]::Parse($item.targetDate)',
    '                $diff = ($target - $today).Days',
    '                $ddayText = ""',
    '                $badgeColor = "#3B82F6"',
    '',
    '                if ($diff -eq 0) {',
    '                    $ddayText = "D-DAY"',
    '                    $badgeColor = "#EF4444"',
    '                } elseif ($diff -gt 0) {',
    '                    $ddayText = "D-$diff"',
    '                    if ($diff -le 7) { $badgeColor = "#F59E0B" } else { $badgeColor = "#10B981" }',
    '                } else {',
    '                    $ddayText = "D+$([Math]::Abs($diff))"',
    '                    $badgeColor = "#64748B"',
    '                }',
    '',
    '                $badge = New-Object System.Windows.Controls.Border',
    '                $badge.CornerRadius = [System.Windows.CornerRadius]6',
    `                $badge.Background = (New-Object System.Windows.Media.BrushConverter).ConvertFromString("${badgeBg}")`,
    '                $badge.BorderBrush = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($badgeColor)',
    '                $badge.BorderThickness = [System.Windows.Thickness]1',
    '                $badge.Padding = [System.Windows.Thickness](New-Object System.Windows.Thickness(6, 2, 6, 2))',
    '                $badge.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(0, 0, 6, 4))',
    '',
    '                $sp = New-Object System.Windows.Controls.StackPanel',
    '                $sp.Orientation = [System.Windows.Controls.Orientation]::Horizontal',
    '',
    '                $title = New-Object System.Windows.Controls.TextBlock',
    '                $title.Text = "$($item.title) "',
    '                $title.FontSize = 11',
    `                $title.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString("${textSecondary}")`,
    '',
    '                $val = New-Object System.Windows.Controls.TextBlock',
    '                $val.Text = $ddayText',
    '                $val.FontSize = 11',
    '                $val.FontWeight = [System.Windows.FontWeights]::Bold',
    '                $val.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($badgeColor)',
    '',
    '                $sp.Children.Add($title) | Out-Null',
    '                $sp.Children.Add($val) | Out-Null',
    '                $badge.Child = $sp',
    '',
    '                $Global:PnlDDays.Children.Add($badge) | Out-Null',
    '            } catch { }',
    '        }',
    '    }',
    '',
    '    # 8. 시간표 렌더링 함수 (1-4교시 / 5-7교시 2열 배치로 글씨 잘림 방지)',
    '    function Update-Timetable {',
    '        $Global:PnlTimetable.Children.Clear()',
    '        $now = Get-Date',
    '        $dayOfWeekIndex = [int]$now.DayOfWeek',
    '        $daysKorean = @("일", "월", "화", "수", "목", "금", "토")',
    '        $dayName = $daysKorean[$dayOfWeekIndex]',
    '        $Global:TxtDayOfWeek.Text = "($($dayName)요일)"',
    '',
    '        $targetDay = "월"',
    '        if ($dayOfWeekIndex -ge 1 -and $dayOfWeekIndex -le 5) { $targetDay = $dayName }',
    '        $todaySchedule = $Global:TimetableData | Where-Object { $_.day -eq $targetDay }',
    '',
    '        if ($todaySchedule -and $todaySchedule.periods) {',
    '            # 2열 메인 그리드 생성',
    '            $grid = New-Object System.Windows.Controls.Grid',
    '            $col1 = New-Object System.Windows.Controls.ColumnDefinition',
    '            $col1.Width = [System.Windows.GridLength](New-Object System.Windows.GridLength(1, [System.Windows.GridUnitType]::Star))',
    '            $col2 = New-Object System.Windows.Controls.ColumnDefinition',
    '            $col2.Width = [System.Windows.GridLength](New-Object System.Windows.GridLength(1, [System.Windows.GridUnitType]::Star))',
    '            $grid.ColumnDefinitions.Add($col1)',
    '            $grid.ColumnDefinitions.Add($col2)',
    '',
    '            # 좌측 패널: 1~4교시 (오전)',
    '            $pnlLeft = New-Object System.Windows.Controls.StackPanel',
    '            $pnlLeft.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(0, 0, 4, 0))',
    '            [System.Windows.Controls.Grid]::SetColumn($pnlLeft, 0)',
    '',
    '            # 우측 패널: 5~7교시 (오후)',
    '            $pnlRight = New-Object System.Windows.Controls.StackPanel',
    '            $pnlRight.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(4, 0, 0, 0))',
    '            [System.Windows.Controls.Grid]::SetColumn($pnlRight, 1)',
    '',
    '            $periods = $todaySchedule.periods',
    '            for ($i = 0; $i -lt $periods.Count; $i++) {',
    '                $periodNum = $i + 1',
    '                $subject = "-"',
    '                if ($periods[$i]) { $subject = $periods[$i] }',
    '',
    '                $itemBorder = New-Object System.Windows.Controls.Border',
    '                $itemBorder.CornerRadius = [System.Windows.CornerRadius]6',
    `                $itemBorder.Background = (New-Object System.Windows.Media.BrushConverter).ConvertFromString("#15FFFFFF")`,
    `                $itemBorder.BorderBrush = (New-Object System.Windows.Media.BrushConverter).ConvertFromString("${cardBorder}")`,
    '                $itemBorder.BorderThickness = [System.Windows.Thickness]1',
    '                $itemBorder.Padding = [System.Windows.Thickness](New-Object System.Windows.Thickness(5, 3, 5, 3))',
    '                $itemBorder.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(0, 1, 0, 2))',
    '',
    '                $itemGrid = New-Object System.Windows.Controls.Grid',
    '                $cNum = New-Object System.Windows.Controls.ColumnDefinition',
    '                $cNum.Width = [System.Windows.GridLength]::Auto',
    '                $cSub = New-Object System.Windows.Controls.ColumnDefinition',
    '                $cSub.Width = [System.Windows.GridLength](New-Object System.Windows.GridLength(1, [System.Windows.GridUnitType]::Star))',
    '                $itemGrid.ColumnDefinitions.Add($cNum)',
    '                $itemGrid.ColumnDefinitions.Add($cSub)',
    '',
    '                $periodColor = if ($periodNum -le 4) { "${accentColor}" } else { "#10B981" }',
    '                $txtNum = New-Object System.Windows.Controls.TextBlock',
    '                $txtNum.Text = "$($periodNum)교시 "',
    '                $txtNum.FontSize = 10',
    '                $txtNum.FontWeight = [System.Windows.FontWeights]::SemiBold',
    '                $txtNum.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($periodColor)',
    '                [System.Windows.Controls.Grid]::SetColumn($txtNum, 0)',
    '',
    '                $txtSub = New-Object System.Windows.Controls.TextBlock',
    '                $txtSub.Text = $subject',
    '                $txtSub.FontSize = 11',
    '                $txtSub.FontWeight = [System.Windows.FontWeights]::Medium',
    '                $txtSub.TextAlignment = [System.Windows.TextAlignment]::Right',
    `                $txtSub.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString("${textPrimary}")`,
    '                [System.Windows.Controls.Grid]::SetColumn($txtSub, 1)',
    '',
    '                $itemGrid.Children.Add($txtNum) | Out-Null',
    '                $itemGrid.Children.Add($txtSub) | Out-Null',
    '                $itemBorder.Child = $itemGrid',
    '',
    '                if ($periodNum -le 4) {',
    '                    $pnlLeft.Children.Add($itemBorder) | Out-Null',
    '                } else {',
    '                    $pnlRight.Children.Add($itemBorder) | Out-Null',
    '                }',
    '            }',
    '',
    '            $grid.Children.Add($pnlLeft) | Out-Null',
    '            $grid.Children.Add($pnlRight) | Out-Null',
    '            $Global:PnlTimetable.Children.Add($grid) | Out-Null',
    '        }',
    '    }',
    '',
    '    # 9. 나이스(NEIS) 급식 API 호출 (13:30 기준 자동 전환)',
    '    function Update-MealInfo {',
    '        $now = Get-Date',
    '        $currentMins = ($now.Hour * 60) + $now.Minute',
    '        $switchMins  = ($Global:SwitchHour * 60) + $Global:SwitchMinute',
    '',
    '        $isNextDay = $false',
    '        $targetDate = $now',
    '',
    '        if ($currentMins -ge $switchMins) {',
    '            $isNextDay = $true',
    '            $targetDate = $now.AddDays(1)',
    '        }',
    '',
    '        if ($targetDate.DayOfWeek -eq [DayOfWeek]::Saturday) {',
    '            $targetDate = $targetDate.AddDays(2)',
    '            $isNextDay = $true',
    '        } elseif ($targetDate.DayOfWeek -eq [DayOfWeek]::Sunday) {',
    '            $targetDate = $targetDate.AddDays(1)',
    '            $isNextDay = $true',
    '        }',
    '',
    '        $ymd = $targetDate.ToString("yyyyMMdd")',
    '        $monthDay = $targetDate.ToString("M월 d일")',
    '        $daysKorean = @("일", "월", "화", "수", "목", "금", "토")',
    '        $dayName = $daysKorean[[int]$targetDate.DayOfWeek]',
    '',
    '        if ($isNextDay) {',
    '            $Global:TxtMealTitle.Text = "내일의 급식"',
    '            $Global:TxtMealTimeBadge.Text = "$monthDay ($dayName) (13:30 이후)"',
    '        } else {',
    '            $Global:TxtMealTitle.Text = "오늘의 급식"',
    '            $Global:TxtMealTimeBadge.Text = "$monthDay ($dayName)"',
    '        }',
    '',
    '        $url = "https://open.neis.go.kr/hub/mealServiceDietInfo?Type=json&pIndex=1&pSize=5&ATPT_OFCDC_SC_CODE=$($Global:OfficeCode)&SD_SCHUL_CODE=$($Global:SchoolCode)&MLSV_YMD=$ymd"',
    '',
    '        try {',
    '            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12',
    '            $response = Invoke-RestMethod -Uri $url -Method Get -TimeoutSec 5 -ErrorAction Stop',
    '',
    '            if ($response.mealServiceDietInfo -and $response.mealServiceDietInfo[1].row) {',
    '                $rows = $response.mealServiceDietInfo[1].row',
    '                $lunch = $rows | Where-Object { $_.MMEAL_SC_CODE -eq "2" } | Select-Object -First 1',
    '                if (!$lunch) { $lunch = $rows[0] }',
    '',
    '                $rawDish = $lunch.DDISH_NM',
    '                $cleanDish = $rawDish -replace "<br\\s*[/]?>", [Environment]::NewLine',
    '                if (!$Global:ShowAllergies) {',
    '                    $cleanDish = $cleanDish -replace "\\([0-9\\.\\s]+\\)", ""',
    '                }',
    '',
    '                $Global:TxtMealMenu.Text = $cleanDish.Trim()',
    '                $Global:TxtMealCalories.Text = "열량: " + ($lunch.CAL_INFO -replace "<br/>", " ")',
    '            } else {',
    '                $Global:TxtMealMenu.Text = "등록된 급식 정보가 없습니다." + [Environment]::NewLine + "(방학, 휴일 또는 식단 미등록)"',
    '                $Global:TxtMealCalories.Text = ""',
    '            }',
    '        } catch {',
    '            $Global:TxtMealMenu.Text = "급식 정보를 불러올 수 없습니다." + [Environment]::NewLine + "(오프라인 또는 NEIS 서버 점검)"',
    '            $Global:TxtMealCalories.Text = ""',
    '        }',
    '    }',
    '',
    '    # 10. 할 일(TO-DO) 로드, 저장, 렌더링',
    '    function Load-Todos {',
    '        if (Test-Path $Global:TodoFile) {',
    '            try {',
    '                $json = Get-Content $Global:TodoFile -Raw -Encoding UTF8',
    '                return $json | ConvertFrom-Json',
    '            } catch {',
    '                return @()',
    '            }',
    '        }',
    '        return @()',
    '    }',
    '',
    '    function Save-Todos {',
    '        param($todosList)',
    '        $json = $todosList | ConvertTo-Json -Depth 4',
    '        [System.IO.File]::WriteAllText($Global:TodoFile, $json, [System.Text.Encoding]::UTF8)',
    '    }',
    '',
    '    function Render-Todos {',
    '        $Global:PnlTodoList.Children.Clear()',
    '        $todos = Load-Todos',
    '        $remaining = ($todos | Where-Object { !$_.completed }).Count',
    '        $Global:TxtTodoCount.Text = "$remaining개 남음"',
    '',
    '        foreach ($todo in $todos) {',
    '            $itemGrid = New-Object System.Windows.Controls.Grid',
    '            $c1 = New-Object System.Windows.Controls.ColumnDefinition',
    '            $c1.Width = [System.Windows.GridLength](New-Object System.Windows.GridLength(1, [System.Windows.GridUnitType]::Star))',
    '            $c2 = New-Object System.Windows.Controls.ColumnDefinition',
    '            $c2.Width = [System.Windows.GridLength](New-Object System.Windows.GridLength(24, [System.Windows.GridUnitType]::Pixel))',
    '            $itemGrid.ColumnDefinitions.Add($c1)',
    '            $itemGrid.ColumnDefinitions.Add($c2)',
    '            $itemGrid.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(0, 2, 0, 2))',
    '',
    '            $todoColor = if ($todo.completed) { "${textSecondary}" } else { "${textPrimary}" }',
    '            $chk = New-Object System.Windows.Controls.CheckBox',
    '            $chk.Content = $todo.text',
    '            $chk.IsChecked = [bool]$todo.completed',
    '            $chk.FontSize = 11',
    '            $chk.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($todoColor)',
    '            $chk.Tag = $todo.id',
    '            [System.Windows.Controls.Grid]::SetColumn($chk, 0)',
    '',
    '            $chk.Add_Click({',
    '                param($s, $ev)',
    '                $id = $s.Tag',
    '                $curTodos = Load-Todos',
    '                foreach ($t in $curTodos) {',
    '                    if ($t.id -eq $id) {',
    '                        $t.completed = [bool]$s.IsChecked',
    '                    }',
    '                }',
    '                Save-Todos $curTodos',
    '                Render-Todos',
    '            })',
    '',
    '            $btnDel = New-Object System.Windows.Controls.Button',
    '            $btnDel.Content = "✕"',
    '            $btnDel.Width = 20',
    '            $btnDel.Height = 20',
    '            $btnDel.Background = [System.Windows.Media.Brushes]::Transparent',
    `            $btnDel.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString("${textSecondary}")`,
    '            $btnDel.BorderThickness = [System.Windows.Thickness]0',
    '            $btnDel.Cursor = [System.Windows.Input.Cursors]::Hand',
    '            $btnDel.FontSize = 10',
    '            $btnDel.Tag = $todo.id',
    '            [System.Windows.Controls.Grid]::SetColumn($btnDel, 1)',
    '',
    '            $btnDel.Add_Click({',
    '                param($s, $ev)',
    '                $id = $s.Tag',
    '                $curTodos = Load-Todos | Where-Object { $_.id -ne $id }',
    '                Save-Todos $curTodos',
    '                Render-Todos',
    '            })',
    '',
    '            $itemGrid.Children.Add($chk) | Out-Null',
    '            $itemGrid.Children.Add($btnDel) | Out-Null',
    '            $Global:PnlTodoList.Children.Add($itemGrid) | Out-Null',
    '        }',
    '    }',
    '',
    '    function Add-NewTodo {',
    '        $text = $Global:TxtNewTodo.Text.Trim()',
    '        if ($text) {',
    '            $todos = @(Load-Todos)',
    '            $newTodo = [PSCustomObject]@{',
    '                id = (Get-Date).Ticks.ToString()',
    '                text = $text',
    '                completed = $false',
    '                createdAt = (Get-Date).ToString("yyyy-MM-dd HH:mm")',
    '            }',
    '            $todos += $newTodo',
    '            Save-Todos $todos',
    '            $Global:TxtNewTodo.Text = ""',
    '            Render-Todos',
    '        }',
    '    }',
    '',
    '    $Global:BtnAddTodo.Add_Click({ Add-NewTodo })',
    '    $Global:TxtNewTodo.Add_KeyDown({',
    '        param($s, $e)',
    '        if ($e.Key -eq [System.Windows.Input.Key]::Enter) {',
    '            Add-NewTodo',
    '        }',
    '    })',
    '',
    '    # 11. 닫기 및 새로고침 이벤트',
    '    $Global:BtnClose.Add_Click({',
    '        $Global:Window.Close()',
    '    })',
    '',
    '    $Global:BtnRefresh.Add_Click({',
    '        Update-AllData',
    '    })',
    '',
    '    # 12. 시계 및 타이머 (DispatcherTimer)',
    '    function Update-AllData {',
    '        $now = Get-Date',
    '        $daysKorean = @("일", "월", "화", "수", "목", "금", "토")',
    '        $dayName = $daysKorean[[int]$now.DayOfWeek]',
    '        $Global:TxtCurrentDate.Text = $now.ToString("yyyy년 M월 d일") + " ($dayName)"',
    '        $Global:TxtCurrentTime.Text = $now.ToString("tt hh:mm:ss")',
    '',
    '        Update-DDays',
    '        Update-Timetable',
    '        Update-MealInfo',
    '    }',
    '',
    '    $timer = New-Object System.Windows.Threading.DispatcherTimer',
    '    $timer.Interval = [TimeSpan]::FromSeconds(1)',
    '    $timer.Add_Tick({',
    '        $now = Get-Date',
    '        $Global:TxtCurrentTime.Text = $now.ToString("tt hh:mm:ss")',
    '        if ($now.Second -eq 0 -and ($now.Minute -eq 0 -or $now.Minute -eq 30)) {',
    '            Update-AllData',
    '        }',
    '    })',
    '    $timer.Start()',
    '',
    '    # 13. 초기 배치 및 로딩 완료 시 우측 상단 안전 배치',
    '    $Global:Window.WindowStartupLocation = [System.Windows.WindowStartupLocation]::Manual',
    '    try {',
    '        $Global:Window.Left = [System.Windows.SystemParameters]::WorkArea.Right - 350 - $Global:SnapMargin',
    '        $Global:Window.Top = [System.Windows.SystemParameters]::WorkArea.Top + $Global:SnapMargin',
    '    } catch { }',
    '',
    '    $Global:Window.Add_Loaded({',
    '        try {',
    '            Update-AllData',
    '            Render-Todos',
    '            Snap-ToRightTop',
    '        } catch {',
    '            Write-Warning "위젯 초기화 경고: $_"',
    '        }',
    '    })',
    '',
    '    # 14. 윈도우 표시 (모달 대화상자)',
    '    $Global:Window.ShowDialog() | Out-Null',
    '} catch {',
    '    Add-Type -AssemblyName System.Windows.Forms',
    '    [System.Windows.Forms.MessageBox]::Show("학교 생활 위젯 실행 중 오류 발생:`r`n`r`n" + $_.Exception.Message + "`r`n`r`n상세:`r`n" + $_.Exception.ToString(), "학교 생활 위젯 오류", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error)',
    '}',
  ];

  return lines.join('\r\n');
}

/**
 * Generate a 100% standalone, self-contained .bat file
 * that can be double-clicked directly without needing a separate .ps1 file.
 */
export function generateAllInOneBat(config: WidgetConfig): string {
  const psScript = generatePowerShellScript(config);

  const batHeader = [
    '@echo off',
    'setlocal enabledelayedexpansion',
    'title NEWSchoolWidget (학교 생활 위젯)',
    'cd /d "%~dp0"',
    '',
    'rem ============================================================================',
    'rem   [NEWSchoolWidget - 단일 통합 원클릭 실행 배치 파일]',
    'rem   - 별도의 .ps1 파일 없이 이 .bat 파일 하나만으로 즉시 위젯이 실행됩니다.',
    'rem   - Windows ExecutionPolicy 제한을 자동으로 우회(Bypass)하여 즉시 실행합니다.',
    'rem ============================================================================',
    '',
    'set "BAT_PATH=%~f0"',
    'powershell.exe -NoProfile -ExecutionPolicy Bypass -Sta -Command "$f=$env:BAT_PATH; if(Test-Path -LiteralPath $f){ $c=[System.IO.File]::ReadAllText($f,[System.Text.Encoding]::UTF8); $marker=\'###POWERSHELL_START_POINT###\'; $i=$c.IndexOf($marker); if($i -ge 0){ $code=$c.Substring($i+$marker.Length); $tempPs1=[System.IO.Path]::Combine($env:TEMP,\'NEWSchoolWidget_Runner.ps1\'); [System.IO.File]::WriteAllText($tempPs1,$code,[System.Text.Encoding]::UTF8); Start-Process powershell.exe -ArgumentList (\'-NoProfile -ExecutionPolicy Bypass -Sta -WindowStyle Hidden -File `\"\' + $tempPs1 + \'`\"\') } }" >nul 2>&1',
    '',
    'exit /b 0',
    '',
    '###POWERSHELL_START_POINT###',
  ].join('\r\n');

  return `${batHeader}\r\n${psScript}`;
}
